/*
 * This source file was generated by the Gradle 'init' task
 */
package connect.four;

import java.util.Random;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Random rand = new Random();
        System.out.println(new App().getGreeting());
        Board board = new Board();
        byte currentPlayer = 1;
        byte gameValue = 0;
        for(int i = 0; i < 42; i++) {
            gameValue = board.addPiece(rand.nextInt(7), currentPlayer);
            while(gameValue == -1) {
                gameValue = board.addPiece(rand.nextInt(7), currentPlayer);
            }
            board.printBoard();
            System.out.println("");
            if(gameValue != 0) {
                break;
            }
            currentPlayer = (byte) (currentPlayer == 1 ? 2 : 1);
        }
        board.printBoard();
        System.out.println("Game over! Player " + gameValue + " wins!");
    }
}

